//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogAsp.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PollAnswer()
        {
            this.PollVotes = new HashSet<PollVote>();
        }
    
        public int idPollAnswer { get; set; }
        public int idPollQuestion { get; set; }
        public string answer { get; set; }
        public Nullable<int> idLastUserChange { get; set; }
        public Nullable<System.DateTime> LastTimeChange { get; set; }
    
        public virtual PollQuestion PollQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PollVote> PollVotes { get; set; }
    }
}
